In [30]:
import pandas as pd
import numpy as np
df = pd.read_parquet('/Users/scott.mckean/Desktop/3w_compiled_data.parquet')
df.sample(10)

,index,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,...,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state,source_file,timestamp,well_number
106140090,NaN,0.0,40.74247,1.0,1.0,0.0,0.0,NaN,1.0,0.0,...,NaN,55.25087,NaN,0.000000e+00,105.476600,107,0,/3W/7/WELL-00022_20180802233838.parquet,2018-08-06 08:08:07,22
93043315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,118.945200,0,0,/3W/0/WELL-00002_20170216030141.parquet,2017-02-16 07:22:31,2
106534559,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.000000,70.68021,NaN,-1.711613e+38,118.230500,107,0,/3W/7/WELL-00006_20180618103000.parquet,2018-06-18 20:12:34,6
126457784,NaN,100.0,-99.99000,NaN,0.0,0.0,0.0,1.0,0.0,0.0,...,0.003889,NaN,-99.990,5.096852e+01,4.310000,108,1,/3W/8/WELL-00030_20141108012623.parquet,2014-11-09 00:49:57,30
83521736,NaN,45.0,41.00000,NaN,1.0,1.0,0.0,1.0,1.0,1.0,...,2.540761,57.29459,NaN,7.714736e+01,69.956580,0,0,/3W/9/WELL-00041_20190906051807.parquet,2019-09-07 20:57:49,41
87363028,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,NaN,...,0.000000,NaN,NaN,NaN,110.540800,0,0,/3W/0/WELL-00003_20170807090000.parquet,2017-08-07 12:50:25,3
93494238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,116.745300,0,0,/3W/0/WELL-00002_20170309010218.parquet,2017-03-09 02:18:45,2
91817199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,117.345100,0,0,/3W/0/WELL-00002_20170620080254.parquet,2017-06-20 13:19:15,2
107451408,NaN,0.0,43.54568,1.0,1.0,0.0,0.0,NaN,1.0,0.0,...,NaN,53.90870,NaN,0.000000e+00,105.760100,107,0,/3W/7/WELL-00022_20180925003447.parquet,2018-10-01 13:19:44,22
123965207,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,...,1.283708,NaN,25.911,NaN,3.470762,108,1,/3W/8/WELL-00027_20230918170106.parquet,2023-09-21 06:40:25,27

In [31]:
indices = ['timestamp', 'well_number']

vars = [
    'P-PDG',
    'P-TPT',
    'T-TPT',
    'P-MON-CKP',
    'T-JUS-CKP',
    'QGL'
    ]

target = ['state']

In [32]:
x_df = (
    df[vars + indices + target]
    .sort_values(['well_number','timestamp'])
    .ffill().dropna()
    .copy()
)

In [33]:
x_df.reset_index().to_parquet('/Users/scott.mckean/Desktop/3w_clean.parquet', coerce_timestamps="ms")

In [ ]:
events_names = {
    0: 'Normal',
    1: 'Abrupt Increase of BSW',
    2: 'Spurious Closure of DHSV',
    3: 'Severe Slugging',
    4: 'Flow Instability',
    5: 'Rapid Productivity Loss',
    6: 'Quick Restriction in PCK',
    7: 'Scaling in PCK',
    8: 'Hydrate in Production Line'
    }

In [1]:
tag_info = {
    1: {"tag": "P-PDG", "name": "Pressure at the PDG", "unit": "Pa"},
    2: {"tag": "P-TPT", "name": "Pressure at the TPT", "unit": "Pa"},
    3: {"tag": "T-TPT", "name": "Temperature at the TPT", "unit": "degC"},
    4: {"tag": "P-MON-CKP", "name": "Pressure upstream of the PCK", "unit": "Pa"},
    5: {"tag": "T-JUS-CKP", "name": "Temperature downstream of the PCK", "unit": "degC"},
    6: {"tag": "P-JUS-CKGL", "name": "Pressure downstream of the GLCK", "unit": "Pa"},
    7: {"tag": "T-JUS-CKGL", "name": "Temperature downstream of the GLCK", "unit": "degC"},
    8: {"tag": "QGL", "name": "Gas lift flow rate", "unit": "sm^3/s"}
}